// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ug/api/proto/targeting/targeting_be.proto

package targeting

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogicalOp int32

const (
	LogicalOp_UnKnown LogicalOp = 0
	LogicalOp_Or      LogicalOp = 1
	LogicalOp_And     LogicalOp = 2
)

var LogicalOp_name = map[int32]string{
	0: "UnKnown",
	1: "Or",
	2: "And",
}

var LogicalOp_value = map[string]int32{
	"UnKnown": 0,
	"Or":      1,
	"And":     2,
}

func (x LogicalOp) String() string {
	return proto.EnumName(LogicalOp_name, int32(x))
}

func (LogicalOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44328c85ad42824b, []int{0}
}

type Predicate_Value_Type int32

const (
	Predicate_Value_UnKnown Predicate_Value_Type = 0
	Predicate_Value_ID      Predicate_Value_Type = 1
	Predicate_Value_RANGE   Predicate_Value_Type = 2
	Predicate_Value_String  Predicate_Value_Type = 3
)

var Predicate_Value_Type_name = map[int32]string{
	0: "UnKnown",
	1: "ID",
	2: "RANGE",
	3: "String",
}

var Predicate_Value_Type_value = map[string]int32{
	"UnKnown": 0,
	"ID":      1,
	"RANGE":   2,
	"String":  3,
}

func (x Predicate_Value_Type) String() string {
	return proto.EnumName(Predicate_Value_Type_name, int32(x))
}

func (Predicate_Value_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44328c85ad42824b, []int{0, 0, 0}
}

type Predicate struct {
	Not                  bool               `protobuf:"varint,1,opt,name=not,proto3" json:"not,omitempty"`
	Value                []*Predicate_Value `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	Field                string             `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Predicate) Reset()         { *m = Predicate{} }
func (m *Predicate) String() string { return proto.CompactTextString(m) }
func (*Predicate) ProtoMessage()    {}
func (*Predicate) Descriptor() ([]byte, []int) {
	return fileDescriptor_44328c85ad42824b, []int{0}
}

func (m *Predicate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Predicate.Unmarshal(m, b)
}
func (m *Predicate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Predicate.Marshal(b, m, deterministic)
}
func (m *Predicate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Predicate.Merge(m, src)
}
func (m *Predicate) XXX_Size() int {
	return xxx_messageInfo_Predicate.Size(m)
}
func (m *Predicate) XXX_DiscardUnknown() {
	xxx_messageInfo_Predicate.DiscardUnknown(m)
}

var xxx_messageInfo_Predicate proto.InternalMessageInfo

func (m *Predicate) GetNot() bool {
	if m != nil {
		return m.Not
	}
	return false
}

func (m *Predicate) GetValue() []*Predicate_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Predicate) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type Predicate_Value struct {
	Type                 Predicate_Value_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=targeting.Predicate_Value_Type" json:"type,omitempty"`
	Id                   uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Range                *Predicate_Value_Range `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	Str                  string                 `protobuf:"bytes,4,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Predicate_Value) Reset()         { *m = Predicate_Value{} }
func (m *Predicate_Value) String() string { return proto.CompactTextString(m) }
func (*Predicate_Value) ProtoMessage()    {}
func (*Predicate_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_44328c85ad42824b, []int{0, 0}
}

func (m *Predicate_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Predicate_Value.Unmarshal(m, b)
}
func (m *Predicate_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Predicate_Value.Marshal(b, m, deterministic)
}
func (m *Predicate_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Predicate_Value.Merge(m, src)
}
func (m *Predicate_Value) XXX_Size() int {
	return xxx_messageInfo_Predicate_Value.Size(m)
}
func (m *Predicate_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Predicate_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Predicate_Value proto.InternalMessageInfo

func (m *Predicate_Value) GetType() Predicate_Value_Type {
	if m != nil {
		return m.Type
	}
	return Predicate_Value_UnKnown
}

func (m *Predicate_Value) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Predicate_Value) GetRange() *Predicate_Value_Range {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *Predicate_Value) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

type Predicate_Value_Range struct {
	Begin                uint64   `protobuf:"varint,1,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  uint64   `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Predicate_Value_Range) Reset()         { *m = Predicate_Value_Range{} }
func (m *Predicate_Value_Range) String() string { return proto.CompactTextString(m) }
func (*Predicate_Value_Range) ProtoMessage()    {}
func (*Predicate_Value_Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_44328c85ad42824b, []int{0, 0, 0}
}

func (m *Predicate_Value_Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Predicate_Value_Range.Unmarshal(m, b)
}
func (m *Predicate_Value_Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Predicate_Value_Range.Marshal(b, m, deterministic)
}
func (m *Predicate_Value_Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Predicate_Value_Range.Merge(m, src)
}
func (m *Predicate_Value_Range) XXX_Size() int {
	return xxx_messageInfo_Predicate_Value_Range.Size(m)
}
func (m *Predicate_Value_Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Predicate_Value_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Predicate_Value_Range proto.InternalMessageInfo

func (m *Predicate_Value_Range) GetBegin() uint64 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *Predicate_Value_Range) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

// 布尔表达式
type BETree struct {
	Not                  bool       `protobuf:"varint,1,opt,name=not,proto3" json:"not,omitempty"`
	Op                   LogicalOp  `protobuf:"varint,2,opt,name=op,proto3,enum=targeting.LogicalOp" json:"op,omitempty"`
	Predicate            *Predicate `protobuf:"bytes,3,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Betree               []*BETree  `protobuf:"bytes,4,rep,name=betree,proto3" json:"betree,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BETree) Reset()         { *m = BETree{} }
func (m *BETree) String() string { return proto.CompactTextString(m) }
func (*BETree) ProtoMessage()    {}
func (*BETree) Descriptor() ([]byte, []int) {
	return fileDescriptor_44328c85ad42824b, []int{1}
}

func (m *BETree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BETree.Unmarshal(m, b)
}
func (m *BETree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BETree.Marshal(b, m, deterministic)
}
func (m *BETree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BETree.Merge(m, src)
}
func (m *BETree) XXX_Size() int {
	return xxx_messageInfo_BETree.Size(m)
}
func (m *BETree) XXX_DiscardUnknown() {
	xxx_messageInfo_BETree.DiscardUnknown(m)
}

var xxx_messageInfo_BETree proto.InternalMessageInfo

func (m *BETree) GetNot() bool {
	if m != nil {
		return m.Not
	}
	return false
}

func (m *BETree) GetOp() LogicalOp {
	if m != nil {
		return m.Op
	}
	return LogicalOp_UnKnown
}

func (m *BETree) GetPredicate() *Predicate {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (m *BETree) GetBetree() []*BETree {
	if m != nil {
		return m.Betree
	}
	return nil
}

// 定向
type Targeting struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Betree               *BETree  `protobuf:"bytes,2,opt,name=betree,proto3" json:"betree,omitempty"`
	Offline              bool     `protobuf:"varint,3,opt,name=offline,proto3" json:"offline,omitempty"`
	UpdateTime           int64    `protobuf:"varint,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Targeting) Reset()         { *m = Targeting{} }
func (m *Targeting) String() string { return proto.CompactTextString(m) }
func (*Targeting) ProtoMessage()    {}
func (*Targeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_44328c85ad42824b, []int{2}
}

func (m *Targeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Targeting.Unmarshal(m, b)
}
func (m *Targeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Targeting.Marshal(b, m, deterministic)
}
func (m *Targeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Targeting.Merge(m, src)
}
func (m *Targeting) XXX_Size() int {
	return xxx_messageInfo_Targeting.Size(m)
}
func (m *Targeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Targeting.DiscardUnknown(m)
}

var xxx_messageInfo_Targeting proto.InternalMessageInfo

func (m *Targeting) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Targeting) GetBetree() *BETree {
	if m != nil {
		return m.Betree
	}
	return nil
}

func (m *Targeting) GetOffline() bool {
	if m != nil {
		return m.Offline
	}
	return false
}

func (m *Targeting) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

// 转化为DNF的定向表达
type TargetingDNF struct {
	Id                   uint64                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Conjunction          []*TargetingDNF_Conjunction `protobuf:"bytes,2,rep,name=conjunction,proto3" json:"conjunction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *TargetingDNF) Reset()         { *m = TargetingDNF{} }
func (m *TargetingDNF) String() string { return proto.CompactTextString(m) }
func (*TargetingDNF) ProtoMessage()    {}
func (*TargetingDNF) Descriptor() ([]byte, []int) {
	return fileDescriptor_44328c85ad42824b, []int{3}
}

func (m *TargetingDNF) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetingDNF.Unmarshal(m, b)
}
func (m *TargetingDNF) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetingDNF.Marshal(b, m, deterministic)
}
func (m *TargetingDNF) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetingDNF.Merge(m, src)
}
func (m *TargetingDNF) XXX_Size() int {
	return xxx_messageInfo_TargetingDNF.Size(m)
}
func (m *TargetingDNF) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetingDNF.DiscardUnknown(m)
}

var xxx_messageInfo_TargetingDNF proto.InternalMessageInfo

func (m *TargetingDNF) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TargetingDNF) GetConjunction() []*TargetingDNF_Conjunction {
	if m != nil {
		return m.Conjunction
	}
	return nil
}

type TargetingDNF_Conjunction struct {
	Predicate            []*Predicate `protobuf:"bytes,1,rep,name=predicate,proto3" json:"predicate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TargetingDNF_Conjunction) Reset()         { *m = TargetingDNF_Conjunction{} }
func (m *TargetingDNF_Conjunction) String() string { return proto.CompactTextString(m) }
func (*TargetingDNF_Conjunction) ProtoMessage()    {}
func (*TargetingDNF_Conjunction) Descriptor() ([]byte, []int) {
	return fileDescriptor_44328c85ad42824b, []int{3, 0}
}

func (m *TargetingDNF_Conjunction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetingDNF_Conjunction.Unmarshal(m, b)
}
func (m *TargetingDNF_Conjunction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetingDNF_Conjunction.Marshal(b, m, deterministic)
}
func (m *TargetingDNF_Conjunction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetingDNF_Conjunction.Merge(m, src)
}
func (m *TargetingDNF_Conjunction) XXX_Size() int {
	return xxx_messageInfo_TargetingDNF_Conjunction.Size(m)
}
func (m *TargetingDNF_Conjunction) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetingDNF_Conjunction.DiscardUnknown(m)
}

var xxx_messageInfo_TargetingDNF_Conjunction proto.InternalMessageInfo

func (m *TargetingDNF_Conjunction) GetPredicate() []*Predicate {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func init() {
	proto.RegisterEnum("targeting.LogicalOp", LogicalOp_name, LogicalOp_value)
	proto.RegisterEnum("targeting.Predicate_Value_Type", Predicate_Value_Type_name, Predicate_Value_Type_value)
	proto.RegisterType((*Predicate)(nil), "targeting.Predicate")
	proto.RegisterType((*Predicate_Value)(nil), "targeting.Predicate.Value")
	proto.RegisterType((*Predicate_Value_Range)(nil), "targeting.Predicate.Value.Range")
	proto.RegisterType((*BETree)(nil), "targeting.BETree")
	proto.RegisterType((*Targeting)(nil), "targeting.Targeting")
	proto.RegisterType((*TargetingDNF)(nil), "targeting.TargetingDNF")
	proto.RegisterType((*TargetingDNF_Conjunction)(nil), "targeting.TargetingDNF.Conjunction")
}

func init() {
	proto.RegisterFile("ug/api/proto/targeting/targeting_be.proto", fileDescriptor_44328c85ad42824b)
}

var fileDescriptor_44328c85ad42824b = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x65, 0xd7, 0x76, 0x5a, 0x8f, 0x51, 0x65, 0x56, 0x3d, 0x58, 0x39, 0xd0, 0x28, 0x70, 0x48,
	0x38, 0xac, 0x91, 0x2b, 0x71, 0x4f, 0x69, 0x40, 0xa8, 0xa8, 0x45, 0x4b, 0xe0, 0xc0, 0xa5, 0x72,
	0xec, 0x89, 0xb5, 0x28, 0xd9, 0x35, 0x66, 0x03, 0xf4, 0xc8, 0x97, 0x70, 0xe5, 0xbf, 0xf8, 0x0c,
	0x2e, 0xc8, 0xeb, 0xc4, 0x31, 0x6a, 0x0a, 0xb7, 0xd9, 0x9d, 0xf7, 0xe6, 0xbd, 0x99, 0xd9, 0x85,
	0xf1, 0xba, 0x88, 0xd3, 0x52, 0xc6, 0x65, 0xa5, 0x8d, 0x8e, 0x4d, 0x5a, 0x15, 0x68, 0xa4, 0x2a,
	0x76, 0xd1, 0xf5, 0x1c, 0xb9, 0x4d, 0x32, 0xbf, 0xbd, 0x1b, 0xfe, 0xa2, 0xe0, 0xbf, 0xa9, 0x30,
	0x97, 0x59, 0x6a, 0x90, 0x85, 0xe0, 0x28, 0x6d, 0x22, 0x32, 0x20, 0xa3, 0x43, 0x51, 0x87, 0xec,
	0x29, 0x78, 0x5f, 0xd2, 0xe5, 0x1a, 0x23, 0x3a, 0x70, 0x46, 0x41, 0xd2, 0xe7, 0x2d, 0x95, 0xb7,
	0x34, 0xfe, 0xbe, 0x46, 0x88, 0x06, 0xc8, 0x8e, 0xc1, 0x5b, 0x48, 0x5c, 0xe6, 0x91, 0x33, 0x20,
	0x23, 0x5f, 0x34, 0x87, 0xfe, 0x6f, 0x02, 0x9e, 0x85, 0xb1, 0x53, 0x70, 0xcd, 0x4d, 0x89, 0x56,
	0xe4, 0x28, 0x39, 0xb9, 0xbb, 0x20, 0x9f, 0xdd, 0x94, 0x28, 0x2c, 0x98, 0x1d, 0x01, 0x95, 0x79,
	0x44, 0x07, 0x64, 0xe4, 0x0a, 0x2a, 0x73, 0xf6, 0x0c, 0xbc, 0x2a, 0x55, 0x05, 0x5a, 0x91, 0x20,
	0x19, 0xfc, 0xa3, 0x8a, 0xa8, 0x71, 0xa2, 0x81, 0xd7, 0x0d, 0x7e, 0x36, 0x55, 0xe4, 0x5a, 0x6b,
	0x75, 0xd8, 0x8f, 0xc1, 0xb3, 0x88, 0xda, 0xf7, 0x1c, 0x0b, 0xa9, 0xac, 0x31, 0x57, 0x34, 0x87,
	0x9a, 0x80, 0x6a, 0xab, 0x5c, 0x87, 0xc3, 0x04, 0xdc, 0xda, 0x18, 0x0b, 0xe0, 0xe0, 0x9d, 0xba,
	0x50, 0xfa, 0xab, 0x0a, 0xef, 0xb1, 0x1e, 0xd0, 0x57, 0xe7, 0x21, 0x61, 0x3e, 0x78, 0x62, 0x72,
	0xf9, 0x72, 0x1a, 0x52, 0x06, 0xd0, 0x7b, 0x6b, 0x2a, 0xa9, 0x8a, 0xd0, 0x19, 0xfe, 0x20, 0xd0,
	0x3b, 0x9b, 0xce, 0x2a, 0xdc, 0x37, 0xe2, 0xc7, 0x40, 0x75, 0x69, 0x15, 0x8e, 0x92, 0xe3, 0x4e,
	0x23, 0xaf, 0x75, 0x21, 0xb3, 0x74, 0x79, 0x55, 0x0a, 0xaa, 0x4b, 0x96, 0x80, 0x5f, 0x6e, 0x3b,
	0xdb, 0x74, 0x7d, 0xbc, 0xaf, 0x6b, 0xb1, 0x83, 0xb1, 0x31, 0xf4, 0xe6, 0x68, 0x2a, 0xc4, 0xc8,
	0xb5, 0xdb, 0x7b, 0xd0, 0x21, 0x34, 0x76, 0xc4, 0x06, 0x30, 0xfc, 0x4e, 0xc0, 0x9f, 0x6d, 0x93,
	0x9b, 0x71, 0x93, 0x76, 0xdc, 0xbb, 0x42, 0xd4, 0x2a, 0xdf, 0x5d, 0x88, 0x45, 0x70, 0xa0, 0x17,
	0x8b, 0xa5, 0x54, 0x8d, 0xcb, 0x43, 0xb1, 0x3d, 0xb2, 0x13, 0x08, 0xd6, 0x65, 0x9e, 0x1a, 0xbc,
	0x36, 0x72, 0x85, 0x76, 0x07, 0x8e, 0x80, 0xe6, 0x6a, 0x26, 0x57, 0x38, 0xfc, 0x49, 0xe0, 0x7e,
	0xeb, 0xe1, 0xfc, 0xf2, 0xc5, 0x2d, 0x1b, 0x53, 0x08, 0x32, 0xad, 0x3e, 0xae, 0x55, 0x66, 0xa4,
	0x56, 0x9b, 0x27, 0xf9, 0xa8, 0xe3, 0xa5, 0xcb, 0xe6, 0xcf, 0x77, 0x50, 0xd1, 0xe5, 0xf5, 0x27,
	0x10, 0x74, 0x72, 0x7f, 0x4f, 0x96, 0xd8, 0x9a, 0xff, 0x9b, 0xec, 0x93, 0x31, 0xf8, 0xed, 0x7a,
	0x6e, 0xbd, 0x84, 0xab, 0x2a, 0x24, 0xec, 0x00, 0x9c, 0x89, 0xca, 0x43, 0x7a, 0x76, 0x01, 0x0f,
	0x33, 0xbd, 0xe2, 0x06, 0x55, 0x86, 0xca, 0xf0, 0x75, 0xd1, 0x7c, 0xc2, 0x9d, 0xc2, 0x87, 0x71,
	0x21, 0x0d, 0xcf, 0x74, 0x8e, 0x5c, 0xa7, 0x3c, 0xd3, 0xab, 0xf8, 0xdb, 0xa7, 0x78, 0xff, 0x67,
	0x9e, 0xf7, 0xec, 0xc5, 0xe9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0x6e, 0x6b, 0x80, 0xed,
	0x03, 0x00, 0x00,
}
