// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ug/api/proto/targeting/targeting_index.proto

package targeting

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Interval struct {
	Begin                uint64   `protobuf:"varint,1,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  uint64   `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interval) Reset()         { *m = Interval{} }
func (m *Interval) String() string { return proto.CompactTextString(m) }
func (*Interval) ProtoMessage()    {}
func (*Interval) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c87b936bd98e62e, []int{0}
}

func (m *Interval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interval.Unmarshal(m, b)
}
func (m *Interval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interval.Marshal(b, m, deterministic)
}
func (m *Interval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interval.Merge(m, src)
}
func (m *Interval) XXX_Size() int {
	return xxx_messageInfo_Interval.Size(m)
}
func (m *Interval) XXX_DiscardUnknown() {
	xxx_messageInfo_Interval.DiscardUnknown(m)
}

var xxx_messageInfo_Interval proto.InternalMessageInfo

func (m *Interval) GetBegin() uint64 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *Interval) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

type IntervalCoverIndex struct {
	Points               []*IntervalCoverIndex_PointInfo `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *IntervalCoverIndex) Reset()         { *m = IntervalCoverIndex{} }
func (m *IntervalCoverIndex) String() string { return proto.CompactTextString(m) }
func (*IntervalCoverIndex) ProtoMessage()    {}
func (*IntervalCoverIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c87b936bd98e62e, []int{1}
}

func (m *IntervalCoverIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntervalCoverIndex.Unmarshal(m, b)
}
func (m *IntervalCoverIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntervalCoverIndex.Marshal(b, m, deterministic)
}
func (m *IntervalCoverIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntervalCoverIndex.Merge(m, src)
}
func (m *IntervalCoverIndex) XXX_Size() int {
	return xxx_messageInfo_IntervalCoverIndex.Size(m)
}
func (m *IntervalCoverIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_IntervalCoverIndex.DiscardUnknown(m)
}

var xxx_messageInfo_IntervalCoverIndex proto.InternalMessageInfo

func (m *IntervalCoverIndex) GetPoints() []*IntervalCoverIndex_PointInfo {
	if m != nil {
		return m.Points
	}
	return nil
}

type IntervalCoverIndex_PointInfo struct {
	Point                uint64   `protobuf:"varint,1,opt,name=point,proto3" json:"point,omitempty"`
	Ids                  []uint32 `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntervalCoverIndex_PointInfo) Reset()         { *m = IntervalCoverIndex_PointInfo{} }
func (m *IntervalCoverIndex_PointInfo) String() string { return proto.CompactTextString(m) }
func (*IntervalCoverIndex_PointInfo) ProtoMessage()    {}
func (*IntervalCoverIndex_PointInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c87b936bd98e62e, []int{1, 0}
}

func (m *IntervalCoverIndex_PointInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntervalCoverIndex_PointInfo.Unmarshal(m, b)
}
func (m *IntervalCoverIndex_PointInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntervalCoverIndex_PointInfo.Marshal(b, m, deterministic)
}
func (m *IntervalCoverIndex_PointInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntervalCoverIndex_PointInfo.Merge(m, src)
}
func (m *IntervalCoverIndex_PointInfo) XXX_Size() int {
	return xxx_messageInfo_IntervalCoverIndex_PointInfo.Size(m)
}
func (m *IntervalCoverIndex_PointInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_IntervalCoverIndex_PointInfo.DiscardUnknown(m)
}

var xxx_messageInfo_IntervalCoverIndex_PointInfo proto.InternalMessageInfo

func (m *IntervalCoverIndex_PointInfo) GetPoint() uint64 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *IntervalCoverIndex_PointInfo) GetIds() []uint32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type IdIndex struct {
	TargetingId          uint64   `protobuf:"varint,1,opt,name=targeting_id,json=targetingId,proto3" json:"targeting_id,omitempty"`
	LocalId              uint32   `protobuf:"varint,2,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdIndex) Reset()         { *m = IdIndex{} }
func (m *IdIndex) String() string { return proto.CompactTextString(m) }
func (*IdIndex) ProtoMessage()    {}
func (*IdIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c87b936bd98e62e, []int{2}
}

func (m *IdIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdIndex.Unmarshal(m, b)
}
func (m *IdIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdIndex.Marshal(b, m, deterministic)
}
func (m *IdIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdIndex.Merge(m, src)
}
func (m *IdIndex) XXX_Size() int {
	return xxx_messageInfo_IdIndex.Size(m)
}
func (m *IdIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_IdIndex.DiscardUnknown(m)
}

var xxx_messageInfo_IdIndex proto.InternalMessageInfo

func (m *IdIndex) GetTargetingId() uint64 {
	if m != nil {
		return m.TargetingId
	}
	return 0
}

func (m *IdIndex) GetLocalId() uint32 {
	if m != nil {
		return m.LocalId
	}
	return 0
}

type TokenIndex struct {
	ConjunctionHit       []*TokenIndex_ConjunctionHit `protobuf:"bytes,1,rep,name=conjunction_hit,json=conjunctionHit,proto3" json:"conjunction_hit,omitempty"`
	TargetingHit         []*TokenIndex_TargetingHit   `protobuf:"bytes,2,rep,name=targeting_hit,json=targetingHit,proto3" json:"targeting_hit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TokenIndex) Reset()         { *m = TokenIndex{} }
func (m *TokenIndex) String() string { return proto.CompactTextString(m) }
func (*TokenIndex) ProtoMessage()    {}
func (*TokenIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c87b936bd98e62e, []int{3}
}

func (m *TokenIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenIndex.Unmarshal(m, b)
}
func (m *TokenIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenIndex.Marshal(b, m, deterministic)
}
func (m *TokenIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenIndex.Merge(m, src)
}
func (m *TokenIndex) XXX_Size() int {
	return xxx_messageInfo_TokenIndex.Size(m)
}
func (m *TokenIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenIndex.DiscardUnknown(m)
}

var xxx_messageInfo_TokenIndex proto.InternalMessageInfo

func (m *TokenIndex) GetConjunctionHit() []*TokenIndex_ConjunctionHit {
	if m != nil {
		return m.ConjunctionHit
	}
	return nil
}

func (m *TokenIndex) GetTargetingHit() []*TokenIndex_TargetingHit {
	if m != nil {
		return m.TargetingHit
	}
	return nil
}

type TokenIndex_ConjunctionHit struct {
	ConjunctionId        uint32   `protobuf:"varint,1,opt,name=conjunction_id,json=conjunctionId,proto3" json:"conjunction_id,omitempty"`
	PredicateId          uint32   `protobuf:"varint,2,opt,name=predicate_id,json=predicateId,proto3" json:"predicate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenIndex_ConjunctionHit) Reset()         { *m = TokenIndex_ConjunctionHit{} }
func (m *TokenIndex_ConjunctionHit) String() string { return proto.CompactTextString(m) }
func (*TokenIndex_ConjunctionHit) ProtoMessage()    {}
func (*TokenIndex_ConjunctionHit) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c87b936bd98e62e, []int{3, 0}
}

func (m *TokenIndex_ConjunctionHit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenIndex_ConjunctionHit.Unmarshal(m, b)
}
func (m *TokenIndex_ConjunctionHit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenIndex_ConjunctionHit.Marshal(b, m, deterministic)
}
func (m *TokenIndex_ConjunctionHit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenIndex_ConjunctionHit.Merge(m, src)
}
func (m *TokenIndex_ConjunctionHit) XXX_Size() int {
	return xxx_messageInfo_TokenIndex_ConjunctionHit.Size(m)
}
func (m *TokenIndex_ConjunctionHit) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenIndex_ConjunctionHit.DiscardUnknown(m)
}

var xxx_messageInfo_TokenIndex_ConjunctionHit proto.InternalMessageInfo

func (m *TokenIndex_ConjunctionHit) GetConjunctionId() uint32 {
	if m != nil {
		return m.ConjunctionId
	}
	return 0
}

func (m *TokenIndex_ConjunctionHit) GetPredicateId() uint32 {
	if m != nil {
		return m.PredicateId
	}
	return 0
}

type TokenIndex_TargetingHit struct {
	LocalId              uint32   `protobuf:"varint,1,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`
	IsId                 bool     `protobuf:"varint,2,opt,name=is_id,json=isId,proto3" json:"is_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenIndex_TargetingHit) Reset()         { *m = TokenIndex_TargetingHit{} }
func (m *TokenIndex_TargetingHit) String() string { return proto.CompactTextString(m) }
func (*TokenIndex_TargetingHit) ProtoMessage()    {}
func (*TokenIndex_TargetingHit) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c87b936bd98e62e, []int{3, 1}
}

func (m *TokenIndex_TargetingHit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenIndex_TargetingHit.Unmarshal(m, b)
}
func (m *TokenIndex_TargetingHit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenIndex_TargetingHit.Marshal(b, m, deterministic)
}
func (m *TokenIndex_TargetingHit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenIndex_TargetingHit.Merge(m, src)
}
func (m *TokenIndex_TargetingHit) XXX_Size() int {
	return xxx_messageInfo_TokenIndex_TargetingHit.Size(m)
}
func (m *TokenIndex_TargetingHit) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenIndex_TargetingHit.DiscardUnknown(m)
}

var xxx_messageInfo_TokenIndex_TargetingHit proto.InternalMessageInfo

func (m *TokenIndex_TargetingHit) GetLocalId() uint32 {
	if m != nil {
		return m.LocalId
	}
	return 0
}

func (m *TokenIndex_TargetingHit) GetIsId() bool {
	if m != nil {
		return m.IsId
	}
	return false
}

type ConjunctionIndex struct {
	HitCount             uint32   `protobuf:"varint,1,opt,name=hit_count,json=hitCount,proto3" json:"hit_count,omitempty"`
	LocalIds             []uint32 `protobuf:"varint,2,rep,packed,name=local_ids,json=localIds,proto3" json:"local_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConjunctionIndex) Reset()         { *m = ConjunctionIndex{} }
func (m *ConjunctionIndex) String() string { return proto.CompactTextString(m) }
func (*ConjunctionIndex) ProtoMessage()    {}
func (*ConjunctionIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c87b936bd98e62e, []int{4}
}

func (m *ConjunctionIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConjunctionIndex.Unmarshal(m, b)
}
func (m *ConjunctionIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConjunctionIndex.Marshal(b, m, deterministic)
}
func (m *ConjunctionIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConjunctionIndex.Merge(m, src)
}
func (m *ConjunctionIndex) XXX_Size() int {
	return xxx_messageInfo_ConjunctionIndex.Size(m)
}
func (m *ConjunctionIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_ConjunctionIndex.DiscardUnknown(m)
}

var xxx_messageInfo_ConjunctionIndex proto.InternalMessageInfo

func (m *ConjunctionIndex) GetHitCount() uint32 {
	if m != nil {
		return m.HitCount
	}
	return 0
}

func (m *ConjunctionIndex) GetLocalIds() []uint32 {
	if m != nil {
		return m.LocalIds
	}
	return nil
}

type TargetingInfo struct {
	TargetingId          int64    `protobuf:"varint,1,opt,name=targeting_id,json=targetingId,proto3" json:"targeting_id,omitempty"`
	TargetingBe          []byte   `protobuf:"bytes,2,opt,name=targeting_be,json=targetingBe,proto3" json:"targeting_be,omitempty"`
	Offline              bool     `protobuf:"varint,3,opt,name=offline,proto3" json:"offline,omitempty"`
	UpdateTime           uint64   `protobuf:"varint,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TargetingInfo) Reset()         { *m = TargetingInfo{} }
func (m *TargetingInfo) String() string { return proto.CompactTextString(m) }
func (*TargetingInfo) ProtoMessage()    {}
func (*TargetingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c87b936bd98e62e, []int{5}
}

func (m *TargetingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetingInfo.Unmarshal(m, b)
}
func (m *TargetingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetingInfo.Marshal(b, m, deterministic)
}
func (m *TargetingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetingInfo.Merge(m, src)
}
func (m *TargetingInfo) XXX_Size() int {
	return xxx_messageInfo_TargetingInfo.Size(m)
}
func (m *TargetingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TargetingInfo proto.InternalMessageInfo

func (m *TargetingInfo) GetTargetingId() int64 {
	if m != nil {
		return m.TargetingId
	}
	return 0
}

func (m *TargetingInfo) GetTargetingBe() []byte {
	if m != nil {
		return m.TargetingBe
	}
	return nil
}

func (m *TargetingInfo) GetOffline() bool {
	if m != nil {
		return m.Offline
	}
	return false
}

func (m *TargetingInfo) GetUpdateTime() uint64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type SearchTokenIndex struct {
	CoverIndex           *IntervalCoverIndex `protobuf:"bytes,1,opt,name=cover_index,json=coverIndex,proto3" json:"cover_index,omitempty"`
	StringIndex          map[string]uint32   `protobuf:"bytes,2,rep,name=string_index,json=stringIndex,proto3" json:"string_index,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SearchTokenIndex) Reset()         { *m = SearchTokenIndex{} }
func (m *SearchTokenIndex) String() string { return proto.CompactTextString(m) }
func (*SearchTokenIndex) ProtoMessage()    {}
func (*SearchTokenIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c87b936bd98e62e, []int{6}
}

func (m *SearchTokenIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTokenIndex.Unmarshal(m, b)
}
func (m *SearchTokenIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTokenIndex.Marshal(b, m, deterministic)
}
func (m *SearchTokenIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTokenIndex.Merge(m, src)
}
func (m *SearchTokenIndex) XXX_Size() int {
	return xxx_messageInfo_SearchTokenIndex.Size(m)
}
func (m *SearchTokenIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTokenIndex.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTokenIndex proto.InternalMessageInfo

func (m *SearchTokenIndex) GetCoverIndex() *IntervalCoverIndex {
	if m != nil {
		return m.CoverIndex
	}
	return nil
}

func (m *SearchTokenIndex) GetStringIndex() map[string]uint32 {
	if m != nil {
		return m.StringIndex
	}
	return nil
}

type TargetingIndex struct {
	SearchTokenIndex     map[string]*SearchTokenIndex `protobuf:"bytes,1,rep,name=search_token_index,json=searchTokenIndex,proto3" json:"search_token_index,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TokenIndex           []*TokenIndex                `protobuf:"bytes,2,rep,name=token_index,json=tokenIndex,proto3" json:"token_index,omitempty"`
	ConjunctionIndex     []*ConjunctionIndex          `protobuf:"bytes,3,rep,name=conjunction_index,json=conjunctionIndex,proto3" json:"conjunction_index,omitempty"`
	IdIndex              []*IdIndex                   `protobuf:"bytes,4,rep,name=id_index,json=idIndex,proto3" json:"id_index,omitempty"`
	Targeting            []*Targeting                 `protobuf:"bytes,5,rep,name=targeting,proto3" json:"targeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TargetingIndex) Reset()         { *m = TargetingIndex{} }
func (m *TargetingIndex) String() string { return proto.CompactTextString(m) }
func (*TargetingIndex) ProtoMessage()    {}
func (*TargetingIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c87b936bd98e62e, []int{7}
}

func (m *TargetingIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetingIndex.Unmarshal(m, b)
}
func (m *TargetingIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetingIndex.Marshal(b, m, deterministic)
}
func (m *TargetingIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetingIndex.Merge(m, src)
}
func (m *TargetingIndex) XXX_Size() int {
	return xxx_messageInfo_TargetingIndex.Size(m)
}
func (m *TargetingIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetingIndex.DiscardUnknown(m)
}

var xxx_messageInfo_TargetingIndex proto.InternalMessageInfo

func (m *TargetingIndex) GetSearchTokenIndex() map[string]*SearchTokenIndex {
	if m != nil {
		return m.SearchTokenIndex
	}
	return nil
}

func (m *TargetingIndex) GetTokenIndex() []*TokenIndex {
	if m != nil {
		return m.TokenIndex
	}
	return nil
}

func (m *TargetingIndex) GetConjunctionIndex() []*ConjunctionIndex {
	if m != nil {
		return m.ConjunctionIndex
	}
	return nil
}

func (m *TargetingIndex) GetIdIndex() []*IdIndex {
	if m != nil {
		return m.IdIndex
	}
	return nil
}

func (m *TargetingIndex) GetTargeting() []*Targeting {
	if m != nil {
		return m.Targeting
	}
	return nil
}

func init() {
	proto.RegisterType((*Interval)(nil), "targeting.Interval")
	proto.RegisterType((*IntervalCoverIndex)(nil), "targeting.IntervalCoverIndex")
	proto.RegisterType((*IntervalCoverIndex_PointInfo)(nil), "targeting.IntervalCoverIndex.PointInfo")
	proto.RegisterType((*IdIndex)(nil), "targeting.IdIndex")
	proto.RegisterType((*TokenIndex)(nil), "targeting.TokenIndex")
	proto.RegisterType((*TokenIndex_ConjunctionHit)(nil), "targeting.TokenIndex.ConjunctionHit")
	proto.RegisterType((*TokenIndex_TargetingHit)(nil), "targeting.TokenIndex.TargetingHit")
	proto.RegisterType((*ConjunctionIndex)(nil), "targeting.ConjunctionIndex")
	proto.RegisterType((*TargetingInfo)(nil), "targeting.TargetingInfo")
	proto.RegisterType((*SearchTokenIndex)(nil), "targeting.SearchTokenIndex")
	proto.RegisterMapType((map[string]uint32)(nil), "targeting.SearchTokenIndex.StringIndexEntry")
	proto.RegisterType((*TargetingIndex)(nil), "targeting.TargetingIndex")
	proto.RegisterMapType((map[string]*SearchTokenIndex)(nil), "targeting.TargetingIndex.SearchTokenIndexEntry")
}

func init() {
	proto.RegisterFile("ug/api/proto/targeting/targeting_index.proto", fileDescriptor_0c87b936bd98e62e)
}

var fileDescriptor_0c87b936bd98e62e = []byte{
	// 705 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0x56, 0xda, 0x6e, 0x6d, 0x4f, 0xda, 0xfd, 0xfa, 0x0b, 0x9b, 0x14, 0x3a, 0x01, 0x23, 0x02,
	0xb1, 0x49, 0x23, 0x15, 0x9d, 0x84, 0x10, 0x17, 0x43, 0xda, 0x84, 0xb6, 0x08, 0x10, 0xc8, 0xdb,
	0xd5, 0x24, 0x54, 0x52, 0xdb, 0x6b, 0xcd, 0x5a, 0xbb, 0x24, 0xee, 0xb4, 0xbd, 0x02, 0x57, 0x3c,
	0x0d, 0xd7, 0xbc, 0x0b, 0x2f, 0x82, 0xec, 0xfc, 0x73, 0xba, 0x08, 0xee, 0x7c, 0x4e, 0xce, 0x9f,
	0xef, 0x7c, 0xe7, 0xb3, 0x03, 0xfb, 0xcb, 0xc9, 0x20, 0x5c, 0xb0, 0xc1, 0x22, 0x12, 0x52, 0x0c,
	0x64, 0x18, 0x4d, 0xa8, 0x64, 0x7c, 0x52, 0x9c, 0x46, 0x8c, 0x13, 0x7a, 0xe3, 0xeb, 0xef, 0x4e,
	0x3b, 0x77, 0xf7, 0xf7, 0xfe, 0x99, 0x38, 0xa6, 0x49, 0x96, 0x37, 0x84, 0x56, 0xc0, 0x25, 0x8d,
	0xae, 0xc3, 0x99, 0xb3, 0x09, 0x6b, 0x63, 0x3a, 0x61, 0xdc, 0xb5, 0x76, 0xac, 0xdd, 0x06, 0x4a,
	0x0c, 0xa7, 0x07, 0x75, 0xca, 0x89, 0x5b, 0xd3, 0x3e, 0x75, 0xf4, 0xbe, 0x5b, 0xe0, 0x64, 0x49,
	0xc7, 0xe2, 0x9a, 0x46, 0x81, 0x82, 0xe1, 0xbc, 0x81, 0xf5, 0x85, 0x60, 0x5c, 0xc6, 0xae, 0xb5,
	0x53, 0xdf, 0xb5, 0x87, 0xcf, 0xfc, 0xbc, 0x9f, 0x7f, 0x37, 0xdc, 0xff, 0xa4, 0x62, 0x03, 0x7e,
	0x29, 0x50, 0x9a, 0xd6, 0x3f, 0x80, 0x76, 0xee, 0x54, 0x60, 0xb4, 0x3b, 0x03, 0xa3, 0x0d, 0x05,
	0x86, 0x91, 0xd8, 0xad, 0xed, 0xd4, 0x77, 0xbb, 0x48, 0x1d, 0xbd, 0x13, 0x68, 0x06, 0x24, 0x01,
	0xf0, 0x18, 0x3a, 0x06, 0x35, 0x24, 0xcd, 0xb4, 0x73, 0x5f, 0x40, 0x9c, 0xfb, 0xd0, 0x9a, 0x09,
	0x1c, 0xce, 0xd4, 0x67, 0x35, 0x51, 0x17, 0x35, 0xb5, 0x1d, 0x10, 0xef, 0x57, 0x0d, 0xe0, 0x5c,
	0x5c, 0x51, 0x9e, 0x14, 0xfb, 0x00, 0xff, 0x61, 0xc1, 0xbf, 0x2e, 0x39, 0x96, 0x4c, 0xf0, 0xd1,
	0x94, 0xc9, 0x74, 0xac, 0x27, 0xc6, 0x58, 0x45, 0xbc, 0x7f, 0x5c, 0x04, 0x9f, 0x32, 0x89, 0x36,
	0x70, 0xc9, 0x76, 0x4e, 0xa0, 0x5b, 0x60, 0x53, 0xc5, 0x6a, 0xba, 0x98, 0x57, 0x5d, 0xec, 0x3c,
	0x73, 0xaa, 0x52, 0xc5, 0x50, 0xa7, 0x4c, 0xf6, 0x2f, 0x60, 0xa3, 0xdc, 0xca, 0x79, 0x0a, 0x66,
	0xb3, 0x6c, 0xf0, 0x2e, 0xea, 0x1a, 0xde, 0x80, 0x28, 0x76, 0x16, 0x11, 0x25, 0x0c, 0x87, 0x92,
	0x16, 0xe3, 0xdb, 0xb9, 0x2f, 0x20, 0xfd, 0x43, 0xe8, 0x98, 0x9d, 0x4b, 0x6c, 0x59, 0x25, 0xb6,
	0x9c, 0x7b, 0xb0, 0xc6, 0xe2, 0xac, 0x4c, 0x0b, 0x35, 0x58, 0x1c, 0x10, 0xef, 0x3d, 0xf4, 0x0c,
	0x6c, 0x09, 0x8f, 0xdb, 0xd0, 0x9e, 0x32, 0x39, 0xc2, 0x62, 0x99, 0xee, 0xb2, 0x8b, 0x5a, 0x53,
	0x26, 0x8f, 0x95, 0xad, 0x3e, 0x66, 0x0d, 0xb2, 0xa5, 0xb6, 0xd2, 0x0e, 0xb1, 0xf7, 0xc3, 0x82,
	0x6e, 0x0e, 0x47, 0x6b, 0xa2, 0x6a, 0xc1, 0xf5, 0xf2, 0x82, 0x4b, 0x21, 0x63, 0xaa, 0xe1, 0x75,
	0x8c, 0x90, 0x23, 0xea, 0xb8, 0xd0, 0x14, 0x97, 0x97, 0x33, 0xc6, 0xa9, 0x5b, 0xd7, 0xe0, 0x33,
	0xd3, 0x79, 0x04, 0xf6, 0x72, 0x41, 0x14, 0x3f, 0x92, 0xcd, 0xa9, 0xdb, 0xd0, 0xfa, 0x81, 0xc4,
	0x75, 0xce, 0xe6, 0xd4, 0xfb, 0x6d, 0x41, 0xef, 0x8c, 0x86, 0x11, 0x9e, 0x1a, 0x4a, 0x39, 0x04,
	0x1b, 0x2b, 0x59, 0x27, 0xb7, 0x51, 0x83, 0xb2, 0x87, 0x0f, 0xfe, 0x2a, 0x7e, 0x04, 0xb8, 0xb8,
	0x37, 0x1f, 0xa1, 0x13, 0xcb, 0x28, 0xbf, 0xce, 0xa9, 0x32, 0xf6, 0x8d, 0x02, 0xab, 0x2d, 0xfd,
	0x33, 0x1d, 0xaf, 0xcf, 0x6f, 0xb9, 0x8c, 0x6e, 0x91, 0x1d, 0x17, 0x9e, 0xfe, 0x21, 0xf4, 0x56,
	0x03, 0xd4, 0xc5, 0xb9, 0xa2, 0xb7, 0x1a, 0x5c, 0x1b, 0xa9, 0xa3, 0xba, 0x60, 0xd7, 0xe1, 0x6c,
	0x49, 0x53, 0x21, 0x24, 0xc6, 0xeb, 0xda, 0x2b, 0xcb, 0xfb, 0x59, 0x87, 0x0d, 0x83, 0x78, 0x85,
	0xf1, 0x33, 0x38, 0xb1, 0x06, 0x31, 0x92, 0x0a, 0x45, 0x3e, 0xaa, 0x42, 0x3a, 0x30, 0x35, 0x5c,
	0x4a, 0xbb, 0x03, 0x3c, 0x01, 0xdb, 0x8b, 0x57, 0x29, 0x7c, 0x09, 0xb6, 0x59, 0x37, 0x61, 0x60,
	0xab, 0xf2, 0x6e, 0x20, 0x90, 0x45, 0xde, 0x29, 0xfc, 0x5f, 0x92, 0xbe, 0xce, 0xae, 0xeb, 0xec,
	0x6d, 0x23, 0x7b, 0x55, 0x94, 0xa8, 0x87, 0x57, 0x65, 0xfa, 0x1c, 0x5a, 0x8c, 0xa4, 0x05, 0x1a,
	0xba, 0x80, 0x63, 0x6e, 0x30, 0x79, 0x61, 0x50, 0x93, 0xa5, 0x4f, 0xcd, 0x10, 0x8a, 0xe7, 0xd6,
	0x5d, 0xd3, 0xf1, 0x9b, 0x55, 0x34, 0x20, 0xe3, 0x55, 0xfe, 0x02, 0x5b, 0x95, 0x7c, 0x54, 0xec,
	0xe6, 0x85, 0xb9, 0x9b, 0xf2, 0x2c, 0xab, 0x25, 0x8c, 0xc5, 0x1d, 0xbd, 0x83, 0x87, 0x58, 0xcc,
	0x7d, 0x49, 0x39, 0xa6, 0x5c, 0xfa, 0xcb, 0x49, 0xf2, 0xc8, 0x17, 0xd9, 0x17, 0x7b, 0x13, 0x26,
	0x7d, 0x2c, 0x08, 0xf5, 0x45, 0xe8, 0x63, 0x31, 0x1f, 0xdc, 0x7c, 0x1b, 0x54, 0xff, 0x2c, 0xc6,
	0xeb, 0xda, 0x71, 0xf0, 0x27, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x02, 0xf6, 0x5a, 0x86, 0x06, 0x00,
	0x00,
}
