// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ug/api/proto/pageview/pageview.proto

package pageview

import (
	fmt "fmt"
	rta "github.com/tencentad/martech/api/proto/rta"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pageview struct {
	TraceId              string         `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ProcessTime          int64          `protobuf:"varint,2,opt,name=process_time,json=processTime,proto3" json:"process_time,omitempty"`
	FromPlatform         string         `protobuf:"bytes,3,opt,name=from_platform,json=fromPlatform,proto3" json:"from_platform,omitempty"`
	Device               *Device        `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	HitRtaInfo           []*rta.RTAInfo `protobuf:"bytes,5,rep,name=hit_rta_info,json=hitRtaInfo,proto3" json:"hit_rta_info,omitempty"`
	InnerCostMs          uint32         `protobuf:"varint,6,opt,name=inner_cost_ms,json=innerCostMs,proto3" json:"inner_cost_ms,omitempty"`
	Imp                  []*Imp         `protobuf:"bytes,7,rep,name=imp,proto3" json:"imp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Pageview) Reset()         { *m = Pageview{} }
func (m *Pageview) String() string { return proto.CompactTextString(m) }
func (*Pageview) ProtoMessage()    {}
func (*Pageview) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd847525d1c7d21c, []int{0}
}

func (m *Pageview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pageview.Unmarshal(m, b)
}
func (m *Pageview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pageview.Marshal(b, m, deterministic)
}
func (m *Pageview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pageview.Merge(m, src)
}
func (m *Pageview) XXX_Size() int {
	return xxx_messageInfo_Pageview.Size(m)
}
func (m *Pageview) XXX_DiscardUnknown() {
	xxx_messageInfo_Pageview.DiscardUnknown(m)
}

var xxx_messageInfo_Pageview proto.InternalMessageInfo

func (m *Pageview) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Pageview) GetProcessTime() int64 {
	if m != nil {
		return m.ProcessTime
	}
	return 0
}

func (m *Pageview) GetFromPlatform() string {
	if m != nil {
		return m.FromPlatform
	}
	return ""
}

func (m *Pageview) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *Pageview) GetHitRtaInfo() []*rta.RTAInfo {
	if m != nil {
		return m.HitRtaInfo
	}
	return nil
}

func (m *Pageview) GetInnerCostMs() uint32 {
	if m != nil {
		return m.InnerCostMs
	}
	return 0
}

func (m *Pageview) GetImp() []*Imp {
	if m != nil {
		return m.Imp
	}
	return nil
}

type Device struct {
	Imei                 string   `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`
	Idfa                 string   `protobuf:"bytes,2,opt,name=idfa,proto3" json:"idfa,omitempty"`
	Oaid                 string   `protobuf:"bytes,3,opt,name=oaid,proto3" json:"oaid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd847525d1c7d21c, []int{1}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *Device) GetIdfa() string {
	if m != nil {
		return m.Idfa
	}
	return ""
}

func (m *Device) GetOaid() string {
	if m != nil {
		return m.Oaid
	}
	return ""
}

type Imp struct {
	Click                []*Click `protobuf:"bytes,1,rep,name=click,proto3" json:"click,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Imp) Reset()         { *m = Imp{} }
func (m *Imp) String() string { return proto.CompactTextString(m) }
func (*Imp) ProtoMessage()    {}
func (*Imp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd847525d1c7d21c, []int{2}
}

func (m *Imp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Imp.Unmarshal(m, b)
}
func (m *Imp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Imp.Marshal(b, m, deterministic)
}
func (m *Imp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Imp.Merge(m, src)
}
func (m *Imp) XXX_Size() int {
	return xxx_messageInfo_Imp.Size(m)
}
func (m *Imp) XXX_DiscardUnknown() {
	xxx_messageInfo_Imp.DiscardUnknown(m)
}

var xxx_messageInfo_Imp proto.InternalMessageInfo

func (m *Imp) GetClick() []*Click {
	if m != nil {
		return m.Click
	}
	return nil
}

type Click struct {
	ClickTime            int64         `protobuf:"varint,1,opt,name=click_time,json=clickTime,proto3" json:"click_time,omitempty"`
	Conversion           []*Conversion `protobuf:"bytes,2,rep,name=conversion,proto3" json:"conversion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Click) Reset()         { *m = Click{} }
func (m *Click) String() string { return proto.CompactTextString(m) }
func (*Click) ProtoMessage()    {}
func (*Click) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd847525d1c7d21c, []int{3}
}

func (m *Click) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Click.Unmarshal(m, b)
}
func (m *Click) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Click.Marshal(b, m, deterministic)
}
func (m *Click) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Click.Merge(m, src)
}
func (m *Click) XXX_Size() int {
	return xxx_messageInfo_Click.Size(m)
}
func (m *Click) XXX_DiscardUnknown() {
	xxx_messageInfo_Click.DiscardUnknown(m)
}

var xxx_messageInfo_Click proto.InternalMessageInfo

func (m *Click) GetClickTime() int64 {
	if m != nil {
		return m.ClickTime
	}
	return 0
}

func (m *Click) GetConversion() []*Conversion {
	if m != nil {
		return m.Conversion
	}
	return nil
}

type Conversion struct {
	ActionTime           int64    `protobuf:"varint,1,opt,name=action_time,json=actionTime,proto3" json:"action_time,omitempty"`
	ActionType           string   `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversion) Reset()         { *m = Conversion{} }
func (m *Conversion) String() string { return proto.CompactTextString(m) }
func (*Conversion) ProtoMessage()    {}
func (*Conversion) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd847525d1c7d21c, []int{4}
}

func (m *Conversion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversion.Unmarshal(m, b)
}
func (m *Conversion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversion.Marshal(b, m, deterministic)
}
func (m *Conversion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversion.Merge(m, src)
}
func (m *Conversion) XXX_Size() int {
	return xxx_messageInfo_Conversion.Size(m)
}
func (m *Conversion) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversion.DiscardUnknown(m)
}

var xxx_messageInfo_Conversion proto.InternalMessageInfo

func (m *Conversion) GetActionTime() int64 {
	if m != nil {
		return m.ActionTime
	}
	return 0
}

func (m *Conversion) GetActionType() string {
	if m != nil {
		return m.ActionType
	}
	return ""
}

func init() {
	proto.RegisterType((*Pageview)(nil), "pageview.Pageview")
	proto.RegisterType((*Device)(nil), "pageview.Device")
	proto.RegisterType((*Imp)(nil), "pageview.Imp")
	proto.RegisterType((*Click)(nil), "pageview.Click")
	proto.RegisterType((*Conversion)(nil), "pageview.Conversion")
}

func init() {
	proto.RegisterFile("ug/api/proto/pageview/pageview.proto", fileDescriptor_dd847525d1c7d21c)
}

var fileDescriptor_dd847525d1c7d21c = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0xc9, 0x5d, 0xef, 0x7a, 0x9d, 0xdc, 0xa1, 0x2c, 0x3e, 0x44, 0xa1, 0x34, 0xa6, 0x0a,
	0x79, 0x90, 0x0d, 0x54, 0xbf, 0x80, 0xb6, 0x2f, 0x79, 0x50, 0xca, 0xd2, 0x27, 0x11, 0xc2, 0xba,
	0xd9, 0xa4, 0x83, 0xdd, 0xec, 0xba, 0xd9, 0x9e, 0xde, 0x77, 0xf0, 0x43, 0x4b, 0x26, 0xe9, 0xdd,
	0x09, 0x3e, 0x04, 0x66, 0x7e, 0xf3, 0xcf, 0xfc, 0x67, 0x86, 0x85, 0x37, 0x8f, 0x6d, 0x21, 0x1d,
	0x16, 0xce, 0xdb, 0x60, 0x0b, 0x27, 0x5b, 0xbd, 0x45, 0xfd, 0x6b, 0x1f, 0x70, 0xe2, 0x6c, 0xf5,
	0x94, 0xbf, 0xba, 0xfc, 0x47, 0xef, 0x83, 0x1c, 0xbe, 0xaa, 0x0f, 0x5e, 0x06, 0xdd, 0xee, 0x46,
	0x79, 0xf6, 0x67, 0x06, 0xab, 0xdb, 0xe9, 0x0f, 0xf6, 0x12, 0x56, 0xc1, 0x4b, 0xa5, 0x2b, 0xac,
	0x93, 0x28, 0x8d, 0xf2, 0x33, 0x71, 0x4a, 0x79, 0x59, 0xb3, 0xd7, 0xb0, 0x76, 0xde, 0x2a, 0xdd,
	0xf7, 0x55, 0x40, 0xa3, 0x93, 0x59, 0x1a, 0xe5, 0x73, 0x11, 0x4f, 0xec, 0x0e, 0x8d, 0x66, 0x97,
	0xb0, 0x69, 0xbc, 0x35, 0x95, 0x7b, 0x90, 0xa1, 0xb1, 0xde, 0x24, 0x73, 0x6a, 0xb1, 0x1e, 0xe0,
	0xed, 0xc4, 0x58, 0x0e, 0xcb, 0x5a, 0x6f, 0x51, 0xe9, 0xe4, 0x24, 0x8d, 0xf2, 0xf8, 0xea, 0x39,
	0xdf, 0xcf, 0x7f, 0x43, 0x5c, 0x4c, 0x75, 0xc6, 0x61, 0x7d, 0x8f, 0xa1, 0x1a, 0x66, 0xc6, 0xae,
	0xb1, 0xc9, 0x22, 0x9d, 0xe7, 0xf1, 0xd5, 0x9a, 0xfb, 0x20, 0xb9, 0xb8, 0xfb, 0x58, 0x76, 0x8d,
	0x15, 0x70, 0x8f, 0x41, 0x04, 0x39, 0xc4, 0x2c, 0x83, 0x0d, 0x76, 0x9d, 0xf6, 0x95, 0xb2, 0x7d,
	0xa8, 0x4c, 0x9f, 0x2c, 0xd3, 0x28, 0xdf, 0x88, 0x98, 0xe0, 0xb5, 0xed, 0xc3, 0xe7, 0x9e, 0x5d,
	0xc0, 0x1c, 0x8d, 0x4b, 0x4e, 0xa9, 0xd5, 0xe6, 0x60, 0x5d, 0x1a, 0x27, 0x86, 0x4a, 0x76, 0x03,
	0xcb, 0x71, 0x0c, 0xc6, 0xe0, 0x04, 0x8d, 0xc6, 0xe9, 0x0e, 0x14, 0x13, 0xab, 0x1b, 0x49, 0xcb,
	0x0f, 0xac, 0x6e, 0xe4, 0xc0, 0xac, 0xc4, 0x7a, 0x5a, 0x96, 0xe2, 0xec, 0x1d, 0xcc, 0x4b, 0xe3,
	0xd8, 0x5b, 0x58, 0xa8, 0x07, 0x54, 0x3f, 0x92, 0x88, 0xfc, 0x9e, 0x1d, 0xfc, 0xae, 0x07, 0x2c,
	0xc6, 0x6a, 0xf6, 0x0d, 0x16, 0x94, 0xb3, 0x73, 0x00, 0x22, 0xe3, 0x85, 0x23, 0xba, 0xf0, 0x19,
	0x11, 0xba, 0xef, 0x07, 0x00, 0x65, 0xbb, 0xad, 0xf6, 0x3d, 0xda, 0x2e, 0x99, 0x51, 0xcf, 0x17,
	0x47, 0x3d, 0xf7, 0x35, 0x71, 0xa4, 0xcb, 0xbe, 0x00, 0x1c, 0x2a, 0xec, 0x02, 0x62, 0xa9, 0x02,
	0xda, 0xee, 0xd8, 0x03, 0x46, 0x44, 0x26, 0x47, 0x82, 0x9d, 0xd3, 0xd3, 0xa6, 0x4f, 0x82, 0x9d,
	0xd3, 0x9f, 0x4a, 0x38, 0x57, 0xd6, 0xf0, 0xa0, 0x3b, 0xa5, 0xbb, 0xc0, 0x1f, 0xdb, 0xf1, 0x21,
	0xed, 0xe7, 0xf8, 0x9a, 0xb7, 0x18, 0xb8, 0xb2, 0xb5, 0xe6, 0x56, 0x72, 0x65, 0x4d, 0xf1, 0xfb,
	0x67, 0xf1, 0xdf, 0x97, 0xfb, 0x7d, 0x49, 0xf9, 0xfb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x78,
	0xc3, 0x75, 0xc1, 0xd9, 0x02, 0x00, 0x00,
}
