// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ug/api/proto/rta/rta_strategy.proto

package rta

import (
	fmt "fmt"
	targeting "github.com/tencentad/martech/api/proto/targeting"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RTA相关信息
type RTAInfo struct {
	Id                   uint64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Betree               *targeting.BETree `protobuf:"bytes,3,opt,name=betree,proto3" json:"betree,omitempty"`
	UpdateTime           int64             `protobuf:"varint,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	BindStrategy         []*BindStrategy   `protobuf:"bytes,5,rep,name=bind_strategy,json=bindStrategy,proto3" json:"bind_strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RTAInfo) Reset()         { *m = RTAInfo{} }
func (m *RTAInfo) String() string { return proto.CompactTextString(m) }
func (*RTAInfo) ProtoMessage()    {}
func (*RTAInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c26dc1a25579049, []int{0}
}

func (m *RTAInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RTAInfo.Unmarshal(m, b)
}
func (m *RTAInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RTAInfo.Marshal(b, m, deterministic)
}
func (m *RTAInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RTAInfo.Merge(m, src)
}
func (m *RTAInfo) XXX_Size() int {
	return xxx_messageInfo_RTAInfo.Size(m)
}
func (m *RTAInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RTAInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RTAInfo proto.InternalMessageInfo

func (m *RTAInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RTAInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RTAInfo) GetBetree() *targeting.BETree {
	if m != nil {
		return m.Betree
	}
	return nil
}

func (m *RTAInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *RTAInfo) GetBindStrategy() []*BindStrategy {
	if m != nil {
		return m.BindStrategy
	}
	return nil
}

// RTA策略实际绑定的策略
type BindStrategy struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Platform             string   `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Strategy             string   `protobuf:"bytes,4,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindStrategy) Reset()         { *m = BindStrategy{} }
func (m *BindStrategy) String() string { return proto.CompactTextString(m) }
func (*BindStrategy) ProtoMessage()    {}
func (*BindStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c26dc1a25579049, []int{1}
}

func (m *BindStrategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindStrategy.Unmarshal(m, b)
}
func (m *BindStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindStrategy.Marshal(b, m, deterministic)
}
func (m *BindStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindStrategy.Merge(m, src)
}
func (m *BindStrategy) XXX_Size() int {
	return xxx_messageInfo_BindStrategy.Size(m)
}
func (m *BindStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_BindStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_BindStrategy proto.InternalMessageInfo

func (m *BindStrategy) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BindStrategy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BindStrategy) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *BindStrategy) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

// 全量的RTA定向信息
type FullRTAInfo struct {
	RtaInfo              []*RTAInfo `protobuf:"bytes,1,rep,name=rta_info,json=rtaInfo,proto3" json:"rta_info,omitempty"`
	DumpTime             int64      `protobuf:"varint,2,opt,name=dump_time,json=dumpTime,proto3" json:"dump_time,omitempty"`
	Version              int64      `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FullRTAInfo) Reset()         { *m = FullRTAInfo{} }
func (m *FullRTAInfo) String() string { return proto.CompactTextString(m) }
func (*FullRTAInfo) ProtoMessage()    {}
func (*FullRTAInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c26dc1a25579049, []int{2}
}

func (m *FullRTAInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullRTAInfo.Unmarshal(m, b)
}
func (m *FullRTAInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullRTAInfo.Marshal(b, m, deterministic)
}
func (m *FullRTAInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullRTAInfo.Merge(m, src)
}
func (m *FullRTAInfo) XXX_Size() int {
	return xxx_messageInfo_FullRTAInfo.Size(m)
}
func (m *FullRTAInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FullRTAInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FullRTAInfo proto.InternalMessageInfo

func (m *FullRTAInfo) GetRtaInfo() []*RTAInfo {
	if m != nil {
		return m.RtaInfo
	}
	return nil
}

func (m *FullRTAInfo) GetDumpTime() int64 {
	if m != nil {
		return m.DumpTime
	}
	return 0
}

func (m *FullRTAInfo) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

// 索引信息，包括倒排和正排信息
type RTAIndex struct {
	Index                *targeting.TargetingIndex `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	RtaTargeting         []*RTAInfo                `protobuf:"bytes,2,rep,name=rta_targeting,json=rtaTargeting,proto3" json:"rta_targeting,omitempty"`
	DumpTime             int64                     `protobuf:"varint,3,opt,name=dump_time,json=dumpTime,proto3" json:"dump_time,omitempty"`
	Version              int64                     `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *RTAIndex) Reset()         { *m = RTAIndex{} }
func (m *RTAIndex) String() string { return proto.CompactTextString(m) }
func (*RTAIndex) ProtoMessage()    {}
func (*RTAIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c26dc1a25579049, []int{3}
}

func (m *RTAIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RTAIndex.Unmarshal(m, b)
}
func (m *RTAIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RTAIndex.Marshal(b, m, deterministic)
}
func (m *RTAIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RTAIndex.Merge(m, src)
}
func (m *RTAIndex) XXX_Size() int {
	return xxx_messageInfo_RTAIndex.Size(m)
}
func (m *RTAIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_RTAIndex.DiscardUnknown(m)
}

var xxx_messageInfo_RTAIndex proto.InternalMessageInfo

func (m *RTAIndex) GetIndex() *targeting.TargetingIndex {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *RTAIndex) GetRtaTargeting() []*RTAInfo {
	if m != nil {
		return m.RtaTargeting
	}
	return nil
}

func (m *RTAIndex) GetDumpTime() int64 {
	if m != nil {
		return m.DumpTime
	}
	return 0
}

func (m *RTAIndex) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*RTAInfo)(nil), "rta.RTAInfo")
	proto.RegisterType((*BindStrategy)(nil), "rta.BindStrategy")
	proto.RegisterType((*FullRTAInfo)(nil), "rta.FullRTAInfo")
	proto.RegisterType((*RTAIndex)(nil), "rta.RTAIndex")
}

func init() {
	proto.RegisterFile("ug/api/proto/rta/rta_strategy.proto", fileDescriptor_9c26dc1a25579049)
}

var fileDescriptor_9c26dc1a25579049 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x95, 0x3f, 0xbb, 0x6d, 0xa7, 0x5d, 0x24, 0x7c, 0x32, 0xe5, 0x40, 0xd4, 0x3d, 0xd0,
	0x95, 0x90, 0x23, 0x16, 0x89, 0x2b, 0xa2, 0x12, 0x48, 0x5c, 0x4d, 0x4f, 0x5c, 0x2a, 0xa7, 0x9e,
	0x46, 0x46, 0xb5, 0x1d, 0xbc, 0x13, 0x54, 0x1e, 0x88, 0x07, 0xe0, 0x0d, 0x51, 0x9c, 0x36, 0xb4,
	0x08, 0x04, 0x87, 0x4a, 0x33, 0xf3, 0x7d, 0x9d, 0xfc, 0x3e, 0xdb, 0x70, 0xdb, 0xd6, 0xa5, 0x6a,
	0x4c, 0xd9, 0x04, 0x4f, 0xbe, 0x0c, 0xa4, 0xba, 0xdf, 0xe6, 0x81, 0x82, 0x22, 0xac, 0xbf, 0x89,
	0x38, 0x66, 0x59, 0x20, 0x35, 0xbf, 0xbb, 0x70, 0x92, 0x0a, 0x35, 0x92, 0x71, 0xf5, 0xaf, 0x6a,
	0x53, 0x61, 0xef, 0x9f, 0xbf, 0xf8, 0xa7, 0xd5, 0x38, 0x8d, 0x87, 0xde, 0xbd, 0xf8, 0x91, 0xc0,
	0x48, 0xae, 0xdf, 0x7e, 0x70, 0x3b, 0xcf, 0x1e, 0x41, 0x6a, 0x34, 0x4f, 0x8a, 0x64, 0x99, 0xcb,
	0xd4, 0x68, 0xc6, 0x20, 0x77, 0xca, 0x22, 0x4f, 0x8b, 0x64, 0x39, 0x91, 0xb1, 0x66, 0x77, 0x70,
	0x5d, 0x21, 0x05, 0x44, 0x9e, 0x15, 0xc9, 0x72, 0x7a, 0xff, 0x58, 0x0c, 0x7b, 0xc5, 0xea, 0xdd,
	0x3a, 0x20, 0xca, 0xa3, 0x81, 0x3d, 0x83, 0x69, 0xdb, 0x68, 0x45, 0xb8, 0x21, 0x63, 0x91, 0xe7,
	0x45, 0xb2, 0xcc, 0x24, 0xf4, 0xa3, 0xb5, 0xb1, 0xc8, 0x5e, 0xc3, 0x4d, 0x65, 0x9c, 0x1e, 0x02,
	0xf3, 0xab, 0x22, 0x8b, 0x2b, 0x03, 0x29, 0xb1, 0x32, 0x4e, 0x7f, 0x3c, 0x0a, 0x72, 0x56, 0x9d,
	0x75, 0x8b, 0xcf, 0x30, 0x3b, 0x57, 0xff, 0x8b, 0x7b, 0x0e, 0xe3, 0x66, 0xaf, 0x68, 0xe7, 0x83,
	0x8d, 0xe4, 0x13, 0x39, 0xf4, 0x9d, 0x36, 0x20, 0xe4, 0xbd, 0x76, 0xea, 0x17, 0x16, 0xa6, 0xef,
	0xdb, 0xfd, 0xfe, 0x74, 0x44, 0xcf, 0x61, 0xdc, 0x5d, 0x91, 0x71, 0x3b, 0xcf, 0x93, 0x48, 0x3b,
	0x8b, 0xb4, 0x47, 0x5d, 0x8e, 0x02, 0xa9, 0x68, 0x7c, 0x0a, 0x13, 0xdd, 0xda, 0xa6, 0x8f, 0x9e,
	0xc6, 0xe8, 0xe3, 0x6e, 0x10, 0x83, 0x73, 0x18, 0x7d, 0xc5, 0xf0, 0x60, 0xbc, 0x8b, 0x2c, 0x99,
	0x3c, 0xb5, 0x8b, 0xef, 0x09, 0x8c, 0xe3, 0x2e, 0x8d, 0x07, 0x56, 0xc2, 0x55, 0xbc, 0xaa, 0x18,
	0x6d, 0x7a, 0xff, 0xe4, 0xec, 0xa8, 0xd7, 0xa7, 0x2a, 0x3a, 0x65, 0xef, 0x63, 0x2f, 0xe1, 0xa6,
	0xa3, 0x1b, 0x6c, 0x3c, 0xfd, 0x03, 0xe2, 0x2c, 0x90, 0x1a, 0xfe, 0x7e, 0xc9, 0x99, 0xfd, 0x9d,
	0x33, 0xbf, 0xe0, 0x5c, 0xbd, 0x01, 0xbe, 0xf5, 0x56, 0x10, 0xba, 0x2d, 0x3a, 0x12, 0x6d, 0xdd,
	0x3f, 0xa7, 0xee, 0x43, 0x9f, 0x6e, 0x6b, 0x43, 0x62, 0xeb, 0x35, 0x0a, 0xaf, 0xc4, 0xd6, 0xdb,
	0xf2, 0xf0, 0xa5, 0xfc, 0xfd, 0xa1, 0x57, 0xd7, 0xb1, 0x7c, 0xf5, 0x33, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0x0a, 0x0f, 0xf9, 0x03, 0x03, 0x00, 0x00,
}
