// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ug/api/proto/retrieval/retrieval.proto

package retrieval

import (
	context "context"
	fmt "fmt"
	rta "github.com/tencentad/martech/api/proto/rta"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Feature_Value_Type int32

const (
	Feature_Value_UnKnown Feature_Value_Type = 0
	Feature_Value_ID      Feature_Value_Type = 1
	Feature_Value_String  Feature_Value_Type = 2
)

var Feature_Value_Type_name = map[int32]string{
	0: "UnKnown",
	1: "ID",
	2: "String",
}

var Feature_Value_Type_value = map[string]int32{
	"UnKnown": 0,
	"ID":      1,
	"String":  2,
}

func (x Feature_Value_Type) String() string {
	return proto.EnumName(Feature_Value_Type_name, int32(x))
}

func (Feature_Value_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a6f03783430ff124, []int{1, 0, 0}
}

type QueryInfoRequest_Cmd int32

const (
	QueryInfoRequest_UnKnown        QueryInfoRequest_Cmd = 0
	QueryInfoRequest_GetTargetingID QueryInfoRequest_Cmd = 1
	QueryInfoRequest_GetTargeting   QueryInfoRequest_Cmd = 2
)

var QueryInfoRequest_Cmd_name = map[int32]string{
	0: "UnKnown",
	1: "GetTargetingID",
	2: "GetTargeting",
}

var QueryInfoRequest_Cmd_value = map[string]int32{
	"UnKnown":        0,
	"GetTargetingID": 1,
	"GetTargeting":   2,
}

func (x QueryInfoRequest_Cmd) String() string {
	return proto.EnumName(QueryInfoRequest_Cmd_name, int32(x))
}

func (QueryInfoRequest_Cmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a6f03783430ff124, []int{3, 0}
}

type RetrievalRequest struct {
	Feature              []*Feature `protobuf:"bytes,2,rep,name=feature,proto3" json:"feature,omitempty"`
	Topn                 int32      `protobuf:"varint,3,opt,name=topn,proto3" json:"topn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RetrievalRequest) Reset()         { *m = RetrievalRequest{} }
func (m *RetrievalRequest) String() string { return proto.CompactTextString(m) }
func (*RetrievalRequest) ProtoMessage()    {}
func (*RetrievalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6f03783430ff124, []int{0}
}

func (m *RetrievalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievalRequest.Unmarshal(m, b)
}
func (m *RetrievalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievalRequest.Marshal(b, m, deterministic)
}
func (m *RetrievalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievalRequest.Merge(m, src)
}
func (m *RetrievalRequest) XXX_Size() int {
	return xxx_messageInfo_RetrievalRequest.Size(m)
}
func (m *RetrievalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievalRequest proto.InternalMessageInfo

func (m *RetrievalRequest) GetFeature() []*Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

func (m *RetrievalRequest) GetTopn() int32 {
	if m != nil {
		return m.Topn
	}
	return 0
}

type Feature struct {
	Field                string           `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value                []*Feature_Value `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6f03783430ff124, []int{1}
}

func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (m *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(m, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Feature) GetValue() []*Feature_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Feature_Value struct {
	Type                 Feature_Value_Type `protobuf:"varint,1,opt,name=type,proto3,enum=retrieval.Feature_Value_Type" json:"type,omitempty"`
	Id                   uint64             `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Str                  string             `protobuf:"bytes,3,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Feature_Value) Reset()         { *m = Feature_Value{} }
func (m *Feature_Value) String() string { return proto.CompactTextString(m) }
func (*Feature_Value) ProtoMessage()    {}
func (*Feature_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6f03783430ff124, []int{1, 0}
}

func (m *Feature_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature_Value.Unmarshal(m, b)
}
func (m *Feature_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature_Value.Marshal(b, m, deterministic)
}
func (m *Feature_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature_Value.Merge(m, src)
}
func (m *Feature_Value) XXX_Size() int {
	return xxx_messageInfo_Feature_Value.Size(m)
}
func (m *Feature_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Feature_Value proto.InternalMessageInfo

func (m *Feature_Value) GetType() Feature_Value_Type {
	if m != nil {
		return m.Type
	}
	return Feature_Value_UnKnown
}

func (m *Feature_Value) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Feature_Value) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

type RetrievalResponse struct {
	RetCode              int32          `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	HitRtaInfo           []*rta.RTAInfo `protobuf:"bytes,3,rep,name=hit_rta_info,json=hitRtaInfo,proto3" json:"hit_rta_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RetrievalResponse) Reset()         { *m = RetrievalResponse{} }
func (m *RetrievalResponse) String() string { return proto.CompactTextString(m) }
func (*RetrievalResponse) ProtoMessage()    {}
func (*RetrievalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6f03783430ff124, []int{2}
}

func (m *RetrievalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievalResponse.Unmarshal(m, b)
}
func (m *RetrievalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievalResponse.Marshal(b, m, deterministic)
}
func (m *RetrievalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievalResponse.Merge(m, src)
}
func (m *RetrievalResponse) XXX_Size() int {
	return xxx_messageInfo_RetrievalResponse.Size(m)
}
func (m *RetrievalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievalResponse proto.InternalMessageInfo

func (m *RetrievalResponse) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *RetrievalResponse) GetHitRtaInfo() []*rta.RTAInfo {
	if m != nil {
		return m.HitRtaInfo
	}
	return nil
}

type QueryInfoRequest struct {
	Cmd                  QueryInfoRequest_Cmd `protobuf:"varint,1,opt,name=cmd,proto3,enum=retrieval.QueryInfoRequest_Cmd" json:"cmd,omitempty"`
	TargetingId          uint64               `protobuf:"varint,2,opt,name=targeting_id,json=targetingId,proto3" json:"targeting_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QueryInfoRequest) Reset()         { *m = QueryInfoRequest{} }
func (m *QueryInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInfoRequest) ProtoMessage()    {}
func (*QueryInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6f03783430ff124, []int{3}
}

func (m *QueryInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryInfoRequest.Unmarshal(m, b)
}
func (m *QueryInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryInfoRequest.Marshal(b, m, deterministic)
}
func (m *QueryInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInfoRequest.Merge(m, src)
}
func (m *QueryInfoRequest) XXX_Size() int {
	return xxx_messageInfo_QueryInfoRequest.Size(m)
}
func (m *QueryInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInfoRequest proto.InternalMessageInfo

func (m *QueryInfoRequest) GetCmd() QueryInfoRequest_Cmd {
	if m != nil {
		return m.Cmd
	}
	return QueryInfoRequest_UnKnown
}

func (m *QueryInfoRequest) GetTargetingId() uint64 {
	if m != nil {
		return m.TargetingId
	}
	return 0
}

type QueryInfoResponse struct {
	Code                 int32        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	TargetingId          []uint64     `protobuf:"varint,2,rep,packed,name=targeting_id,json=targetingId,proto3" json:"targeting_id,omitempty"`
	RtaInfo              *rta.RTAInfo `protobuf:"bytes,3,opt,name=rta_info,json=rtaInfo,proto3" json:"rta_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryInfoResponse) Reset()         { *m = QueryInfoResponse{} }
func (m *QueryInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInfoResponse) ProtoMessage()    {}
func (*QueryInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6f03783430ff124, []int{4}
}

func (m *QueryInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryInfoResponse.Unmarshal(m, b)
}
func (m *QueryInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryInfoResponse.Marshal(b, m, deterministic)
}
func (m *QueryInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInfoResponse.Merge(m, src)
}
func (m *QueryInfoResponse) XXX_Size() int {
	return xxx_messageInfo_QueryInfoResponse.Size(m)
}
func (m *QueryInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInfoResponse proto.InternalMessageInfo

func (m *QueryInfoResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryInfoResponse) GetTargetingId() []uint64 {
	if m != nil {
		return m.TargetingId
	}
	return nil
}

func (m *QueryInfoResponse) GetRtaInfo() *rta.RTAInfo {
	if m != nil {
		return m.RtaInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("retrieval.Feature_Value_Type", Feature_Value_Type_name, Feature_Value_Type_value)
	proto.RegisterEnum("retrieval.QueryInfoRequest_Cmd", QueryInfoRequest_Cmd_name, QueryInfoRequest_Cmd_value)
	proto.RegisterType((*RetrievalRequest)(nil), "retrieval.RetrievalRequest")
	proto.RegisterType((*Feature)(nil), "retrieval.Feature")
	proto.RegisterType((*Feature_Value)(nil), "retrieval.Feature.Value")
	proto.RegisterType((*RetrievalResponse)(nil), "retrieval.RetrievalResponse")
	proto.RegisterType((*QueryInfoRequest)(nil), "retrieval.QueryInfoRequest")
	proto.RegisterType((*QueryInfoResponse)(nil), "retrieval.QueryInfoResponse")
}

func init() {
	proto.RegisterFile("ug/api/proto/retrieval/retrieval.proto", fileDescriptor_a6f03783430ff124)
}

var fileDescriptor_a6f03783430ff124 = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xcb, 0x8e, 0xd3, 0x4a,
	0x10, 0x8d, 0xed, 0x3c, 0x2b, 0x51, 0xe4, 0x69, 0xdd, 0x85, 0x6f, 0x78, 0x05, 0x23, 0x31, 0x41,
	0x42, 0x1d, 0x4d, 0xd8, 0xb0, 0x85, 0x20, 0x86, 0x68, 0x56, 0xf4, 0x04, 0x16, 0x2c, 0x88, 0x8c,
	0x5d, 0xf1, 0xb4, 0x94, 0xb8, 0x3d, 0xed, 0x72, 0x20, 0x1f, 0xc0, 0x8f, 0x20, 0xf1, 0x4d, 0xfc,
	0x0e, 0xb2, 0x9d, 0x87, 0xf3, 0x60, 0x61, 0xa9, 0x7c, 0xea, 0xd4, 0xe3, 0x9c, 0xee, 0x86, 0xe7,
	0x69, 0x38, 0xf4, 0x62, 0x39, 0x8c, 0xb5, 0x22, 0x35, 0xd4, 0x48, 0x5a, 0xe2, 0xca, 0x5b, 0xec,
	0x23, 0x9e, 0x67, 0x58, 0x6b, 0x07, 0xf4, 0x9e, 0x1d, 0x96, 0x90, 0x97, 0x7d, 0xb3, 0x84, 0xb4,
	0x47, 0x18, 0xae, 0x0b, 0xbe, 0x3b, 0x05, 0x5b, 0x6c, 0x2b, 0x04, 0xde, 0xa7, 0x98, 0x10, 0x7b,
	0x09, 0x8d, 0x39, 0x7a, 0x94, 0x6a, 0x74, 0xcc, 0xbe, 0x35, 0x68, 0x8f, 0x18, 0xdf, 0x8f, 0x79,
	0x5f, 0x64, 0xc4, 0x96, 0xc2, 0x18, 0x54, 0x49, 0xc5, 0x91, 0x63, 0xf5, 0x8d, 0x41, 0x4d, 0xe4,
	0xb1, 0xfb, 0xc7, 0x80, 0xc6, 0x86, 0xc8, 0xfe, 0x83, 0xda, 0x5c, 0xe2, 0x22, 0x70, 0x8c, 0xbe,
	0x31, 0x68, 0x89, 0xe2, 0x87, 0x71, 0xa8, 0xad, 0xbc, 0x45, 0xba, 0x9d, 0xe0, 0x9c, 0x4e, 0xe0,
	0x9f, 0xb3, 0xbc, 0x28, 0x68, 0xbd, 0x9f, 0x06, 0xd4, 0x72, 0x80, 0x5d, 0x41, 0x95, 0xd6, 0x31,
	0xe6, 0xed, 0xba, 0xa3, 0x47, 0xff, 0x2a, 0xe4, 0xd3, 0x75, 0x8c, 0x22, 0xa7, 0xb2, 0x2e, 0x98,
	0x32, 0x70, 0xcc, 0xbe, 0x31, 0xa8, 0x0a, 0x53, 0x06, 0xcc, 0x06, 0x2b, 0x21, 0x9d, 0x6f, 0xdc,
	0x12, 0x59, 0xe8, 0x5e, 0x42, 0x35, 0xe3, 0xb3, 0x36, 0x34, 0x3e, 0x45, 0x37, 0x91, 0xfa, 0x1e,
	0xd9, 0x15, 0x56, 0x07, 0x73, 0xf2, 0xce, 0x36, 0x18, 0x40, 0xfd, 0x96, 0xb4, 0x8c, 0x42, 0xdb,
	0x74, 0xbf, 0xc2, 0x45, 0xc9, 0xaf, 0x24, 0x56, 0x51, 0x82, 0xec, 0x7f, 0x68, 0x6a, 0xa4, 0x99,
	0xaf, 0x82, 0x62, 0xad, 0x9a, 0x68, 0x68, 0xa4, 0xb1, 0x0a, 0x90, 0x71, 0xe8, 0xdc, 0x49, 0x9a,
	0x65, 0xce, 0xcb, 0x68, 0xae, 0x1c, 0x2b, 0x97, 0xdb, 0xe1, 0x9a, 0x3c, 0x2e, 0xa6, 0x6f, 0x26,
	0xd1, 0x5c, 0x09, 0xb8, 0x93, 0x24, 0xc8, 0xcb, 0x62, 0xf7, 0x97, 0x01, 0xf6, 0xc7, 0x14, 0xf5,
	0x3a, 0xcf, 0x6c, 0x0e, 0xe4, 0x0a, 0x2c, 0x7f, 0x19, 0x6c, 0x14, 0x3f, 0x29, 0x29, 0x3e, 0x66,
	0xf2, 0xf1, 0x32, 0x10, 0x19, 0x97, 0x3d, 0x85, 0x0e, 0x79, 0x3a, 0x44, 0x92, 0x51, 0x38, 0xdb,
	0x89, 0x6f, 0xef, 0xb0, 0x49, 0xe0, 0xbe, 0x06, 0x6b, 0xbc, 0x0c, 0x0e, 0x25, 0x33, 0xe8, 0x5e,
	0x23, 0x4d, 0x77, 0xac, 0x4c, 0xbe, 0x0d, 0x9d, 0x32, 0x66, 0x9b, 0x6e, 0x02, 0x17, 0xa5, 0xc9,
	0x1b, 0x13, 0x18, 0x54, 0x4b, 0x06, 0xe4, 0xf1, 0x99, 0x2d, 0xac, 0xa3, 0x2d, 0xd8, 0x25, 0x34,
	0x4b, 0xe6, 0x18, 0x27, 0xe6, 0x34, 0x74, 0xe1, 0xcc, 0xe8, 0xb7, 0x51, 0xba, 0xaa, 0xb7, 0xa8,
	0x57, 0xd2, 0x47, 0x76, 0x0d, 0xcd, 0x0d, 0x86, 0xec, 0x41, 0xc9, 0x98, 0xe3, 0x3b, 0xdd, 0x7b,
	0x78, 0x3e, 0x59, 0xec, 0xee, 0x56, 0xd8, 0x07, 0x68, 0xed, 0x24, 0x1d, 0x74, 0x3a, 0xb6, 0xf8,
	0xa0, 0xd3, 0x89, 0x0b, 0x6e, 0xe5, 0xed, 0x0d, 0x3c, 0xf6, 0xd5, 0x92, 0x13, 0x46, 0x3e, 0x46,
	0xc4, 0xd3, 0xb0, 0x78, 0x69, 0xfb, 0xaa, 0x2f, 0x2f, 0x42, 0x49, 0x3c, 0xf3, 0x87, 0x2b, 0x8f,
	0xfb, 0x6a, 0x39, 0xfc, 0x71, 0x3f, 0x3c, 0xff, 0xbc, 0xbf, 0xd5, 0x73, 0xe0, 0xd5, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x08, 0xed, 0x05, 0x7d, 0xff, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RetrievalServiceClient is the client API for RetrievalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RetrievalServiceClient interface {
	Retrieve(ctx context.Context, in *RetrievalRequest, opts ...grpc.CallOption) (*RetrievalResponse, error)
	QueryInfo(ctx context.Context, in *QueryInfoRequest, opts ...grpc.CallOption) (*QueryInfoResponse, error)
}

type retrievalServiceClient struct {
	cc *grpc.ClientConn
}

func NewRetrievalServiceClient(cc *grpc.ClientConn) RetrievalServiceClient {
	return &retrievalServiceClient{cc}
}

func (c *retrievalServiceClient) Retrieve(ctx context.Context, in *RetrievalRequest, opts ...grpc.CallOption) (*RetrievalResponse, error) {
	out := new(RetrievalResponse)
	err := c.cc.Invoke(ctx, "/retrieval.RetrievalService/Retrieve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalServiceClient) QueryInfo(ctx context.Context, in *QueryInfoRequest, opts ...grpc.CallOption) (*QueryInfoResponse, error) {
	out := new(QueryInfoResponse)
	err := c.cc.Invoke(ctx, "/retrieval.RetrievalService/QueryInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RetrievalServiceServer is the server API for RetrievalService service.
type RetrievalServiceServer interface {
	Retrieve(context.Context, *RetrievalRequest) (*RetrievalResponse, error)
	QueryInfo(context.Context, *QueryInfoRequest) (*QueryInfoResponse, error)
}

// UnimplementedRetrievalServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRetrievalServiceServer struct {
}

func (*UnimplementedRetrievalServiceServer) Retrieve(ctx context.Context, req *RetrievalRequest) (*RetrievalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retrieve not implemented")
}
func (*UnimplementedRetrievalServiceServer) QueryInfo(ctx context.Context, req *QueryInfoRequest) (*QueryInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryInfo not implemented")
}

func RegisterRetrievalServiceServer(s *grpc.Server, srv RetrievalServiceServer) {
	s.RegisterService(&_RetrievalService_serviceDesc, srv)
}

func _RetrievalService_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrievalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServiceServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/retrieval.RetrievalService/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServiceServer).Retrieve(ctx, req.(*RetrievalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrievalService_QueryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServiceServer).QueryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/retrieval.RetrievalService/QueryInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServiceServer).QueryInfo(ctx, req.(*QueryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RetrievalService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "retrieval.RetrievalService",
	HandlerType: (*RetrievalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Retrieve",
			Handler:    _RetrievalService_Retrieve_Handler,
		},
		{
			MethodName: "QueryInfo",
			Handler:    _RetrievalService_QueryInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ug/api/proto/retrieval/retrieval.proto",
}
